Using with prepared testing database
mrtnzlml/testbench pull request #38
Opened 2016-10-05 10:32 UTC by clovnrian

- not everyone want setup database automatically (create db, drop db, apply migrations etc.)
- better handling default configuration parameters
- add php.ini for testing with required extensions
- add checkAjaxSignal method for testing signal called from AJAX

2016-10-08 12:30 UTC, mrtnzlml commented
My intention is take a look at this PR as soon as possible. Just letting you know I am aware of this request. Be patient please... :)

2016-10-09 13:22 UTC, mrtnzlml requested changes
Thanks for PR. First of all (for the future reference) please send multiple PR instead of big one. For example in this case it's not acceptable as a whole and therefore I cannot accept it at all.

I implemented on my own these changes:
- `TPresenter::checkAjaxSignal`
- better DI extension parameters handling (with simple validation)
- fixed wrong parameter setting in `TestbenchExtension`
- added support for shared databases via `shareDatabase: yes` option (it behaves quite differently now, but it should be good)

Please look at it if it's good for your use case and if you have time for that please rebase this branch or send another PR and close this one.

Thanks for your help. I really appreciate it.

2016-10-09 13:22 UTC, mrtnzlml commented on src/Mocks/DoctrineConnectionMock.php
> +			} catch(\Doctrine\DBAL\Migrations\MigrationException $e) {
It throws `Could not find any migrations to execute.` and I think this is way better than silently move on. If you don't have migrations, you should use this setting:

```
testbench:
    migrations: no
```

2016-10-09 13:22 UTC, mrtnzlml commented on tests/php.ini
> +
This file should not be needed. Just use `-C` switch or if you are using `vendor/bin/run-tests` it should be enough (no INI file needed).

2016-10-09 13:22 UTC, mrtnzlml commented on src/TestbenchExtension.php
> +							isset($sectionConfig['password']) ? $sectionConfig['password'] : null,
At this moment Testbench only supports MySQL and PostgreSQL. I cannot blindly fix this because I don't fully understand what is the problem here. You should prepare failing test.

2016-10-10 12:35 UTC, clovnrian commented
Thanks for applying some of my changes. I tried your changes in our project and the share database is not what we need. We create SQLite database for tests, so we just need to use the database connection specified in configuration file without any database setup. I will decline my pull request and when I have time I will try add SQLite support to the library.

2016-10-10 12:35 UTC, closed without merging

2016-10-11 08:39 UTC, mrtnzlml commented
Yeah, the thing is that at this moment SQLite is not supported and if you are using for example MySQL in your production - then you should use MySQL in tests. No matter what.

At this moment I have to figure out better database handling in general and after that the database drivers refactoring in Testbench is crucial. Current design is bad and I don't like it. But overall it works quite well (but only with supported databases obviously).

Thanks for understanding, patience and help... :)