Added isLoggedIn to TPresenter
mrtnzlml/testbench pull request #44
Opened 2017-04-22 15:56 UTC by radekhubner

2017-04-24 16:20 UTC, mrtnzlml requested changes
Also please keep coding standard and use tabs instead of spaces. Thanks...

2017-04-24 16:20 UTC, mrtnzlml commented on src/Traits/TPresenter.php
> +    protected function isLoggedIn()
Could you please rename it to `isUserLoggedIn`?

2017-04-24 16:20 UTC, mrtnzlml commented on tests/Traits/TPresenterTest.phpt
> +    {
Please check that user is not logged in at the beginning of the test. Test scenario should be:
- not logged in (test)
- login
- logged in (test)
- logout
- not logged in (test)

2017-04-25 07:05 UTC, mrtnzlml commented on tests/Traits/TPresenterTest.phpt
> +		$this->logOut();
User should be logged out by default (remove this line). Look at the scenario I wrote in previous comment:
- test
- login
- test
- logout
- test

2017-04-26 06:31 UTC, radekhubner commented
@mrtnzlml I edited it.

2017-04-26 17:10 UTC, mrtnzlml approved these changes

2017-04-26 17:11 UTC, merged

2017-04-26 17:12 UTC, mrtnzlml commented
Thank you very much @radekhubner.